packages:
  - "api"
  - "extension-manager"
  - "ds/vuetify"
  - "ds/dsfr"
  - "ds/shoelace"
  - "skin"
  - "macros"
  - "rendering/wikimodel"
  - "rendering/rendering"
  - "storage"
  - "sharedworker/api"
  - "sharedworker/impl"
  - "extensions/menubuttons"
  - "editors/wikitext"
  - "editors/milkdown"
  - "xwiki/remoteinlineeditor"
  - "lib"
  - "web"
  - "electron"
  - "electron/main"
  - "electron/preload"
  - "electron/renderer"
  - "electron/storage"
  - "dev/config"
  - "sources/xwiki/mock-server"
